import Head from "next/head";
import React from "react";
import Navbar from "../Components/Navbar";
import Footer from "../Components/footer";
import {ArrowRightIcon} from "@heroicons/react/outline";

export default function About() {
  return (
    <div className="bg-[url('/images/about-me.gif')] md:bg-[url('/images/about-me1.gif')] bg-contain bg-no-repeat bg-top bg-fixed mt-0">
      <Head>
        <title>Grace Song | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicongs.svg" />
      </Head>

      <Navbar />
      
      <main>
      <div className="flex justify-between text-center mx-0 md:mx-3 lg:mx-5 md:pt-28 pt-28">
         <div className="flex flex-col md:ml-3 mx-5 mt-0">
             <h1 className="font-normal text-[56px] md:text-8xl lg:text-9xl text-left mb-5">
                  A bit about me.
             </h1>
               <div className="pt-0 pb-4 md:pt-4">
                  <div className="w-full border-t border-black border-dotted"></div>
               </div>
               <p1 className="font-['Maison_Neue'] text-sm lg:text-base text-left mt-32 mb-2 md:w-5/6 lg:w-4/6">
                 00 / BRIEF SUMMARY
               </p1>
               <p1 className="font-normal text-3xl lg:text-4xl text-left my-5 md:w-5/6 lg:w-4/6">
                  Following a degree in Graphic Design at OCADu, a keen interest in bettering experiences within our day to day facilitated a subtle yet meaningful transition into UI/UX design.
               </p1>
               <p1 className="font-normal text-lg lg:text-xl text-left my-5 md:w-5/6 lg:w-4/6">
                  During this incredible phase of self-taught learning and hands-on experimentation, I found myself appreciating the grounded knowledge of design fundamentals, in which I was able to intuitively apply within this space of delightful, user-centered design.<br/><br/>Fast forward to covid-free July 2022—I have the privilege of working with startups leading UI/UX as a sole designer, pursuing projects ranging from redesigning a web platform to delivering end-to-end designs for new mobile apps. Jumping into the work environment during unprecedented times was full of uncertainty, however it’s become an invaluable experience collaborating within a remote team, even from the comfort of my home.<br/><br/>As an individual who experiences and appreciates the world as an endless opportunity for learning, I’ve grown to challenge myself in tackling every new idea with an inquisitive mind and a genuine state of curiosity. The art of creating with purpose, meaning and reasoning is what I’d say guides my design process, and being able to contribute to an inspiring community of thoughtful design is an area I feel truly rewarding.
               </p1>
               <div className="pt-6 pb-4">
                  <div className="w-full border-t border-black border-dotted"></div>
               </div>
               <p1 className="font-['Maison_Neue'] text-sm lg:text-base text-left mt-32 mb-2 md:w-5/6 lg:w-4/6">
                 01 / EXPERIENCE
               </p1>
                 <div className="flex flex-col justify-between">
                   <p1 className="font-normal text-3xl lg:text-4xl text-left mt-8 mb-0 md:w-5/6 lg:w-4/6">Lead UI/UX Designer</p1> 
                   <div className="flex flex-row justify-between md:w-5/6 lg:w-4/6 mt-2 mb-10"> 
                     <p1 className="font-normal text-lg lg:text-xl text-left text-zinc-400">Tario Ventures Group</p1>
                     <p1 className="font-normal text-lg lg:text-xl text-right text-zinc-400">Jan 2022 – Present</p1>
                   </div>
                   <p1 className="font-normal text-3xl lg:text-4xl text-left mt-8 mb-0 md:w-5/6 lg:w-4/6">UI/UX Designer</p1> 
                   <div className="flex flex-row justify-between md:w-5/6 lg:w-4/6 mt-2 mb-10"> 
                     <p1 className="font-normal text-lg lg:text-xl text-left text-zinc-400">SalonEverywhere</p1>
                     <p1 className="font-normal text-lg lg:text-xl text-left text-zinc-400">Jan 2021 – Jan 2022</p1>
                   </div>
                   <p1 className="font-normal text-3xl lg:text-4xl text-left mt-8 mb-0 md:w-5/6 lg:w-4/6">Freelance Designer</p1> 
                   <div className="flex flex-row justify-between md:w-5/6 lg:w-4/6 mt-2 mb-10"> 
                     <p1 className="font-normal text-lg lg:text-xl text-left text-zinc-400">Toronto, ON</p1>
                     <p1 className="font-normal text-lg lg:text-xl text-left text-zinc-400">Aug 2019 – Nov 2020</p1>
                   </div>
                   <p1 className="font-normal text-3xl lg:text-4xl text-left mt-8 mb-0 md:w-5/6 lg:w-4/6">Design Intern</p1> 
                   <div className="flex flex-row justify-between md:w-5/6 lg:w-4/6 mt-2 mb-10"> 
                     <p1 className="font-normal text-lg lg:text-xl text-left text-zinc-400">Parmida LED Technologies</p1>
                     <p1 className="font-normal text-lg lg:text-xl text-left text-zinc-400">Mar 2018 ­– Jun 2018</p1>
                   </div>
                   <a href="https://drive.google.com/file/d/169iDF_zXzqZ84h4SLe15ZEvSK23O4DO4/view?usp=sharing" target="_blank" rel="noopener noreferrer" className="flex flex-row items-center font-normal text-3xl lg:text-4xl text-left mt-8 mb-0 md:w-5/6 lg:w-4/6">View Resume <ArrowRightIcon className="h-8 w-8 -rotate-45 ml-2"/></a>
                  </div>
                 <div className="pt-10 pb-4">
                  <div className="w-full border-t border-black border-dotted"></div>
                 </div>
                 <div className="w-full flex flex-col md:flex-row justify-left md:gap-40 lg:gap-60 items-start">
               <div className='py-6'>
                 <p className='text-lg text-left pb-4'>Tools</p>
                 <ul className='text-base text-left text-zinc-400'>
                   <li>Figma</li>
                   <li>Adobe XD</li>
                   <li>Illustrator</li>
                   <li>InDesign</li>
                   <li>Photoshop</li>
                   <li>AfterEffects/Premiere</li>
                   <li>Visual Studio Code</li>
                 </ul>
               </div>
               <div className='py-6'>
                 <p className='text-lg text-left pb-4'>Skill sets</p>
                 <ul className='text-base text-left text-zinc-400'>
                   <li>User-centered design</li>
                   <li>Research and User flows</li>
                   <li>Wireframing and Prototyping</li>
                   <li>Usability testing</li>
                   <li>Visual design</li>
                   <li>Packaging and Branding</li>
                   <li>Editorial and Typography</li>
                   <li>HTML/CSS</li>
                 </ul>
               </div>
               <div className='py-6'>
                 <p className='text-lg text-left pb-4'>Interpersonal</p>
                 <ul className='text-base text-left text-zinc-400'>
                   <li>Punctual</li>
                   <li>Attentive</li>
                   <li>Detail-oriented</li>
                   <li>Empathetic</li>
                   <li>Adaptable</li>
                   <li>Solid work ethic</li>
                 </ul>
               </div>
              </div>
              <div className="pt-6 pb-4">
                <div className="w-full border-t border-black border-dotted"></div>
              </div>

                 <p1 className="font-['Maison_Neue'] text-sm lg:text-base text-left mt-32 mb-2 md:w-5/6 lg:w-4/6">
                    02 / FUN FACTS
                 </p1>
                 <p1 className="font-normal text-3xl lg:text-4xl text-left my-5 md:w-5/6 lg:w-4/6">
                    grown to have awful handwriting · survives on iced coffee <span className="text-zinc-400">even in the cold</span> · enjoys catching sunsets · appreciates typography · finds pleasure in baking <span className="text-zinc-400">blueberry scones</span> · loves anything matcha · codependent on furry friend · keen on self-help books <span className="text-zinc-400">thanks to Mark Manson</span>
                 </p1>
                 <p1 className="font-normal text-3xl lg:text-4xl text-left mt-10 mb-20 md:w-5/6 lg:w-4/6 mt-20">
                    Coming to a close, thank you for making it this far!
                 </p1>

         </div>
      </div>
     </main>
     <Footer />
     </div>
  );
}
