import Head from "next/head";
import Navbar from "../Components/Navbar";
import Footer from "../Components/footer";
import Projects from "../lib/data";
import Projectheader from "../Components/projectheader";
import Image from "next/image";
import CLhero from "../public/images/Four.png";

export default function canadalife() {
    const data = Projects.canadalife;
    const { title, description, overview, brief, heroimage } = Projects.canadalife;

  return (
    <div>
      <Head>
        <title>Grace Song | Canada Life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicongs.svg" />
      </Head>

      <Navbar />
     <Projectheader data={Projects.canadalife}>
     </Projectheader>
     <div className="flex justify-between text-center mx-0 md:mx-3 lg:mx-5 mt-5 md:mt-10">
       <div className="flex flex-col md:ml-3 mx-5 mt-0">
         <div className="mb-20">
          <Image src={CLhero} alt="solution" layout="responsive" objectFit="cover"/>
         </div>
         <p1 className="font-normal tracking-wider text-sm lg:text-base text-left mt-20 mb-2 md:w-5/6 lg:w-4/6">
           01 / THE PROBLEM
         </p1>
         <p1 className="font-normal text-3xl lg:text-4xl text-left my-5 md:w-5/6 lg:w-4/6">
           The homepage for Canada Life has not been restructured for over 5 years and was in need of a refresh to target current issues.
         </p1>
         <p1 className="font-normal text-lg lg:text-xl text-left my-5 md:w-5/6 lg:w-4/6">
           This case study is a work in progress and will be coming soon.
         </p1>
       </div>
      </div>
    <Footer />
    </div>
  );
}