import Head from "next/head";
import Navbar from "../Components/Navbar";
import styles from "../styles/Home.module.css";
import Projectcards from "../Components/Projectcards"
import Intro from "../Components/Intro";
import Footer from "../Components/footer";

export default function Home() {
  return (
    <div className="md:bg-[url('/images/hero-bg.gif')] md:bg-contain md:bg-no-repeat md:bg-top md:mt-0 bg-[url('/images/hero-bg1.gif')] bg-no-repeat bg-contain">
      <Head>
        <title>Grace Song | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicongs.svg" />
      </Head>

      <Navbar />
      <Intro />
      <Projectcards />
      <Footer />
      </div>
  );
  }