import Head from "next/head";
import Navbar from "../Components/Navbar";
import styles from "../styles/Home.module.css";
import Projectcards from "../Components/Projectcards"
import Intro from "../Components/Intro";
import Footer from "../Components/footer";

export default function Home() {
  return (
    <div class="bg-[url('/images/hero-bg.gif')] bg-contain bg-no-repeat bg-top mt-0">
      <Head>
        <title>Grace Song | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicongs.svg" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link href="//db.onlinewebfonts.com/c/63467b9cbd4a4d7eafb5e64946ecaa18?family=Maison+Neue" rel="stylesheet" type="text/css"/>
      </Head>

      <Navbar />
      <Intro />
      <Projectcards />
      <Footer />
      <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
      <script>AOS.init();</script>
      </div>
  );
  }